### ISSUE TITLE
replication & synchronization?

### ISSUE THREAD

**Issue by whatsdis** [noffle/kappa-osm#12]
If I do a query, is replication happening under the hood? Or do we need to do it manually, if so how?

if a peer inserts an element, do other peers automatically see it when they do another query?

**Comment by hackergrrl** [comment]
A query operates on whatever data you have in your local database. Replication is an explicit process where two peers exchange all of their map data.

Your question made me realize that the replication API was somehow missing from the readme! I [just added a section](https://github.com/digidem/kappa-osm#var-stream--osmreplicateopts) on it. Does this help?

**Comment by whatsdis** [comment]
hmm I see. I thought that all peers are automatically synced to a single database....is osm-p2p-server a more appropriate tool?

What I expected was that there was this central database that all peers replicated and kept in sync. Much like the kappa-core chat workshop example utilizing hyperswarm network, whenever somebody pushes to a kappa core feed, all peers are synced.

should I be using https://github.com/mafintosh/hyperdb instead?

**Comment by hackergrrl** [comment]
Every peer has its own full copy of the database. This is true for the
entire stack -- osm-p2p-server included.

You could run this in a configuration that had a central server-like
setup. The server wouldn't be any more authoritative than any other
peer, but it could act as a consistant point that peers can find
reliably to sync up to. You could do replication over, say, a websocket
stream that your web server hosts.
