### ISSUE TITLE
bug: Do not mutate batch operations

### ISSUE THREAD

**Issue by gmaclennan** [noffle/kappa-osm#19]
Currently, `osm.batch(ops)` will mutate `ops` by appending an `id` and `links` to each value:

- https://github.com/digidem/kappa-osm/blob/v3.1.1/index.js#L288-L289
- https://github.com/digidem/kappa-osm/blob/v3.1.1/index.js#L294

This leads to unexpected behaviour, mainly in tests when we use a fixture for batch operations and re-use it in separate instances of the database. It means that operations are not idempotent, e.g.

```
const ops = require('./fixture')

var mapeo1 = createApi()
var mapeo2 = createApi()

mapeo1.osm.batch(ops)
mapeo2.osm.batch(ops)
```

This will result in `mapeo1` and `mapeo2` being in a different state because `ops` is mutated by the first batch operation.

**Comment by hackergrrl** [comment]
Is this blocking anything for you? Asking because if we fix it before we push kappa-osm@4, we'll need to forwardport it.

**Comment by gmaclennan** [comment]
No, I managed to work around it in my tests, just want to leave it here to make sure we remember in v4

**Comment by luandro** [comment]
Not sure I get what the real problem here is.

Are the messages mal-formated and should always have an id and empty links Array before being published?

**Comment by gmaclennan** [comment]
Hi @luandro, the problem is that the `batch(ops)` method will mutate (e.g. add properties to) the `ops` object passed as an argument. The consequence of this is that if you use the same `ops` object in two batch calls in two separate databases, then you will get two different results (because the properties that are added to the `ops` object cause the operations to be different next time the object is used).

In general it is bad practice to mutate a function argument unless it is clearly documented, because it can lead to unexpected bugs.

This particular issue in kappa-osm does not come up in code that we currently use, but it appears in tests and came up for me: I had two different test files, each of which did `var ops = require('fixtures/operations.json')`. When you run tests with tape, all test files are run in the same process, so that `fixtures/operations.json` is only required once and re-used in each test file. Because it is mutated by the `batch()` method, it resulted in unexpected test failing. It was confusing because each test would run independently without error, but would fail when run together (because only when run together were the tests re-using the same object for the operations).

The solution is to clone the `ops` to ensure that the original object is not mutated.
